### ISSUE TITLE
Implement User Activation through Email when Registering

### ISSUE THREAD

**Issue by siddhantkhandelwal** [siddhantkhandelwal/SMS19#3]
## Issue Description

Currently, in User Registration, there is no verification of E-mail Address on Registration.

## ToDo:

- An email with a hash token URL should be sent to the provided E-mail address.
  - Once the user clicks on the link in the E-mail, their Account should get validated.

- If possible, implement Validity Time Limit on the link sent by mail.
  - If the link expires the associated User and UserProfile is deleted.

## Note
Use the credentials provided in SETTINGS.py for sending the e-mails for now.

**Comment by ashryaagr** [comment]
Won't it be better if we use Django Allauth ? It will send the mail automatically . And anyways as SMS is gonna be a big event, so we have to add the feature to login using social accounts/google...and we will have to use Django allauth for it , so why not use it for normal login/signup also .....

**Comment by siddhantkhandelwal** [comment]
That's a good idea, however, we were thinking of dropping Google OAuth this time. It's an unnecessary overhead.
If you are really into it, it would be great if you could create a PR with Google OAuth Implemented referencing this Issue. If it works fine enough we can go with that too. 
Do work on a different branch than master.

Anyways we would have to resolve this issue standalone anyways as we will keep this way of creating accounts too.

**Comment by siddhantkhandelwal** [comment]
@ashryaagr Thanks for Google OAuth!
This issue addresses the concern that we need to have a verification system for users registering by standalone form too.
