### ISSUE TITLE
Exception thrown when registering

### ISSUE THREAD

**Issue by Saujas** [siddhantkhandelwal/SMS19#5]
Programming error occurring when registering. Registration takes place but the screen shows an exception, as attached in the screenshot.

**Comment by Saujas** [comment]
![Screenshot from 2019-03-18 18-48-43](https://user-images.githubusercontent.com/31803919/54533048-4f4c0f80-49af-11e9-9dc5-dd55351a2ca9.png)

**Comment by ashryaagr** [comment]
The migrations are not being applied . Idk why but "python manage.py migrate" is not working, even when I use app name with it .  If you try the command "python manage.py showmigrations" , you won't find the latest migrations in it.
So i dropped the database, created it again , applied migrations and now it is working fine .

**Comment by Saujas** [comment]
https://stackoverflow.com/questions/29902366/django-migration-is-not-applying-the-migration-changes.
Follow this link, or the updated readme file to fix this issue.
